image: node:19.6

variables:
  GIT_DEPTH: 1

stages:
  - build
  - test

# https://docs.gitlab.com/ee/ci/caching/index.html#cache-nodejs-dependencies
cache:
  paths:
    - frontend/.npm/

before_script:
  - cd frontend
  - npm ci --cache .npm --prefer-offline

build-test:
  stage: build
  script:
    - ls -al
