variables:
  GIT_DEPTH: 1

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

build-frontend:
  stage: build
  image: node:19.6
  script:
    - cd frontend
    - npm install
    - npm run build

test-backend-style:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - make test-style

test-backend-api:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - cp $BACKEND_ENV_FILE .env
    - make test-api

postman_tests:
  stage: test
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run Postman.json

frontend_python_tests:
  stage: frontend_tests
  image: python:3.10.7
  services:
    - selenium/standalone-chrome
  before_script:
    - pip3 install selenium
  script:
    - cd front-end && python3 guitests.py
