image: node:19.6

stages:
  - build
  - test

# https://docs.gitlab.com/ee/ci/caching/index.html#cache-nodejs-dependencies
cache:
  paths:
    - front-end/.npm/

before_script:
  - cd front-end
  - npm ci --cache .npm --prefer-offline

build-test:
  stage: build
  script:
    - ls -a
