variables:
  GIT_DEPTH: 1
  PIPELINE_TRIGGER: /^(\s+)?pipeline.*/i

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

build-frontend:
  stage: build
  image: node:19.6
  script:
    - cd frontend
    - npm install
    - npm run build
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

test-backend-style:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - make test-style
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

test-backend-api:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - cp $BACKEND_ENV_FILE .env
    - make test-api
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

postman_tests:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run Postman.json
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

selenium_tests:
  stage: test
  image: python:3.10.6
  services:
    - selenium/standalone-chrome
  before_script:
    - pip3 install selenium
  script:
    - cd frontend
    - python3 -m unittest discover -s tests
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

jest_tests:
  stage: test
  image: node:19.6
  script:
    - cd frontend
    - npm test
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER

frontend_style_tests:
  stage: test
  image: node:19.6
  script:
    - cd frontend
    - npm run lint
    - npm run prettier:check
  rules:
    - if: $CI_COMMIT_DESCRIPTION =~ $PIPELINE_TRIGGER
