image: node:19.6

variables:
  GIT_DEPTH: 1

stages:
  - build
  - test

# https://docs.gitlab.com/ee/ci/caching/index.html#cache-nodejs-dependencies
cache:
  paths:
    - frontend/.npm/

build-test:
  stage: build
  before_script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
  script:
    - ls -al

test:
  stage: test
  script:
    - cd frontend
    - ls -al
