image: node:19.6

variables:
  GIT_DEPTH: 1

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

build-test:
  stage: build
  script:
    - cd frontend
    - npm install
    - ls -al

another-build-test:
  stage: build
  script:
    - cd frontend
    - ls -al

test:
  stage: test
  script:
    - cd frontend
    - ls -al
