variables:
  GIT_DEPTH: 1

stages:
  - build
  - test

cache:
  paths:
    - frontend/node_modules/

build-frontend:
  stage: build
  image: node:19.6
  script:
    - cd frontend
    - npm install
    - npm run build

test-backend-style:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - make test-style

test-backend-api:
  stage: test
  image: python:3.10.6
  script:
    - cd backend
    - pip3 install -r requirements.txt
    - echo "$BACKEND_ENV_FILE" > .env
    - make test-api
